export const TOKENS = Object.freeze({
  config: 'core.config',
  logger: 'core.logger',
  featureFlags: 'core.featureFlags',
  router: 'core.router',
  healthCheck: 'core.healthCheck',
  responseFactory: 'core.responseFactory',
  errorHandler: 'core.errorHandler',
  requestContextFactory: 'core.requestContextFactory',
  version: 'core.version',
  routingProvider: 'routing.provider',
  serverCountryResolver: 'routing.serverCountryResolver',
  routingPreviewEndpoint: 'routing.previewEndpoint',
  leadRepository: 'lead.repository',
  leadValidator: 'lead.validator',
  leadFactory: 'lead.factory',
  leadMapper: 'lead.mapper',
  leadService: 'lead.service',
  leadController: 'lead.controller',
  tokenHasher: 'security.tokenHasher',
  fieldEncryptionProvider: 'security.fieldEncryptionProvider',
  leadRepositoryResolver: 'lead.repositoryResolver',
  databaseProviderRU: 'database.provider.ru',
  databaseProviderInternational: 'database.provider.international'
});
